/* BODHA v0.7.7 — Clean Dashboard Rebuild
   Single dashboard renderer + single dashboard language layer.
   Learning engine remains untouched.
*/
(function(){
  'use strict';
  const PROFILE_KEY='bodhaStudentProfile_v07', DATA_KEY='bodhaLearningData_v07';
  const LANGS=['en','te','hy'], $=id=>document.getElementById(id);
  const getLang=()=>{try{const v=typeof langKey==='function'?langKey():localStorage.getItem('bodhaLanguage');return LANGS.includes(v)?v:'en'}catch(_){return'en'}};
  const COPY={
    en:{accountEyebrow:'BODHA STUDENT PROFILE',createTitle:'Create your student profile',backTitle:'Welcome back',createIntro:'This prototype saves your learning journey on this device.',backIntro:'Your learning profile is saved on this device.',name:'Student name',grade:'Class',namePh:'Enter your name',continue:'Continue to BODHA →',note:'Prototype note: this is local device storage, not a production login.',enterName:'Please enter your name.',dashEyebrow:'BODHA STUDENT DASHBOARD',profile:'Profile',current:'CURRENT LEARNING',diagnosis:'DIAGNOSIS',diagnosisNote:'Initial evidence',focus:'FOCUS SKILL',focusNote:'BODHA learning path',events:'LEARNING EVENTS',eventsNote:'Saved on this device',map:'My Learning Map',evidence:'Evidence',journey:'My Learning Journey',path:'Path',boundary:'Prototype data boundary',boundaryText:'This version uses local browser storage only. It is not a production authentication system or cloud student database.',reset:'Reset prototype student data',subtitle:'Here is your BODHA learning journey and what comes next.',stageProfile:'Your profile is ready. Let’s start with a diagnostic.',stageReady:'Your personalised learning path is ready.',stagePractice:'You are in Adaptive Practice.',nextLabel:'Next step',nextDiagnosis:'Start your initial diagnostic',nextLesson:'Continue to your personalised lesson',nextPractice:'Continue Adaptive Practice',start:'Start My BODHA Journey →',continueLearn:'Continue My Learning →',empty:'Complete the diagnostic to build your Learning Map.',status:{strong:'Strong evidence',developing:'Developing',support:'Needs support'},journeySteps:['Student profile','Initial diagnosis','Personalised lesson','Adaptive practice','Mastery verification','Retention check'],chapter:'Chapter 2 — Linear Equations in One Variable'},
    te:{accountEyebrow:'BODHA STUDENT PROFILE',createTitle:'నీ student profile create చేద్దాం',backTitle:'మళ్లీ స్వాగతం',createIntro:'ఈ prototype నీ learning journey ని ఈ device లో save చేస్తుంది.',backIntro:'నీ learning profile ఈ device లో save అయింది.',name:'విద్యార్థి పేరు',grade:'తరగతి',namePh:'నీ పేరు enter చేయి',continue:'BODHA కి కొనసాగుదాం →',note:'Prototype note: ఇది local device storage మాత్రమే; production login కాదు.',enterName:'నీ పేరు enter చేయి.',dashEyebrow:'BODHA STUDENT DASHBOARD',profile:'Profile',current:'CURRENT LEARNING',diagnosis:'DIAGNOSIS',diagnosisNote:'Initial evidence',focus:'FOCUS SKILL',focusNote:'BODHA learning path',events:'LEARNING EVENTS',eventsNote:'ఈ device లో save అయింది',map:'నా Learning Map',evidence:'Evidence',journey:'నా Learning Journey',path:'Path',boundary:'Prototype data గురించి',boundaryText:'ఈ version లో నీ data ఈ browser లోనే save అవుతుంది. ఇది production login కాదు లేదా cloud student database కాదు.',reset:'Prototype student data reset చేద్దాం',subtitle:'ఇప్పటివరకు నువ్వు ఎలా learn చేశావో, next ఏం చేయాలో ఇక్కడ clear గా చూడొచ్చు.',stageProfile:'ముందుగా Diagnostic చేద్దాం.',stageReady:'నీకు సరిపోయే learning path ready గా ఉంది.',stagePractice:'ఇప్పుడు మనం Adaptive Practice చేస్తున్నాం.',nextLabel:'Next step',nextDiagnosis:'మొదటి diagnostic start చేద్దాం',nextLesson:'నీ personalised lesson continue చేద్దాం',nextPractice:'Adaptive Practice continue చేద్దాం',start:'నా BODHA Journey ప్రారంభిద్దాం →',continueLearn:'నా Learning continue చేద్దాం →',empty:'Diagnostic complete చేద్దాం. అప్పుడు నీ Learning Map ని build చేస్తాం.',status:{strong:'బాగా అర్థమైంది',developing:'ఇంకా practice కావాలి',support:'మరింత support కావాలి'},journeySteps:['నీ student profile','Initial diagnosis','నీకు సరిపోయే lesson','Adaptive practice','Mastery verification','తర్వాత retention check'],chapter:'Chapter 2 — ఒక చరరాశిలో సరళ సమీకరణాలు'},
    hy:{accountEyebrow:'BODHA STUDENT PROFILE',createTitle:'ముందుగా నీ student profile create చేసుకుందాం',backTitle:'మళ్లీ వచ్చావు — welcome back!',createIntro:'ఈ prototype నీ learning journey ని ఈ device లో save చేస్తుంది.',backIntro:'నీ learning profile ఈ device లో save అయింది — ఇప్పుడు learning continue చేద్దాం.',name:'నీ పేరు',grade:'నీ Class',namePh:'నీ name enter చేయి',continue:'BODHA తో continue చేద్దాం →',note:'Prototype note: ఇది local device storage మాత్రమే — production login కాదు.',enterName:'నీ name enter చేయి.',dashEyebrow:'BODHA STUDENT DASHBOARD',profile:'Profile',current:'CURRENT LEARNING',diagnosis:'DIAGNOSIS',diagnosisNote:'Initial evidence',focus:'FOCUS SKILL',focusNote:'BODHA learning path',events:'LEARNING EVENTS',eventsNote:'ఈ device లో save అయింది',map:'నా Learning Map',evidence:'Evidence',journey:'నా Learning Journey',path:'Path',boundary:'Prototype data గురించి',boundaryText:'ఈ version లో నీ data ఈ browser లోనే save అవుతుంది. ఇది production login కాదు లేదా cloud student database కాదు.',reset:'Prototype student data reset చేద్దాం',subtitle:'నీ learning journey, current progress, next step అన్నీ ఇక్కడ clear గా చూడొచ్చు.',stageProfile:'ముందుగా నీ current understanding ని check చేద్దాం.',stageReady:'నీకు సరిపోయే learning path ready గా ఉంది.',stagePractice:'ఇప్పుడు Adaptive Practice చేస్తున్నాం.',nextLabel:'Next step',nextDiagnosis:'మొదటి diagnostic start చేద్దాం',nextLesson:'నీ personalised lesson continue చేద్దాం',nextPractice:'Adaptive Practice continue చేద్దాం',start:'నా BODHA Journey ప్రారంభిద్దాం →',continueLearn:'Learning continue చేద్దాం →',empty:'Diagnostic complete చేద్దాం. అప్పుడు నీ Learning Map ని build చేస్తాం.',status:{strong:'Strong evidence',developing:'ఇంకా practice కావాలి',support:'మరింత support కావాలి'},journeySteps:['నీ student profile','Initial diagnosis','నీకు సరిపోయే lesson','Adaptive practice','Mastery verification','తర్వాత retention check'],chapter:'Chapter 2 — Linear Equations in One Variable'}
  };
  const text=(id,v)=>{const e=$(id);if(e)e.textContent=v};
  const readProfile=()=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch(_){return null}};
  const readData=()=>{const p=readProfile();if(!p)return null;try{const d=JSON.parse(localStorage.getItem(DATA_KEY)||'null');return d&&d.profile&&d.profile.id===p.id?d:{profile:p,chapter:'Chapter 2 — Linear Equations in One Variable',diagnosis:null,learningPath:null,events:[],skills:{},currentStage:'profile',updatedAt:Date.now()}}catch(_){return null}};
  const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}};
  function record(type,payload={}){const d=readData();if(!d)return;d.events=d.events||[];d.events.push({type,at:Date.now(),...payload});d.updatedAt=Date.now();save(DATA_KEY,d)}
  const showScreen=id=>{if(typeof show==='function')show(id)};
  function renderAccount(){
    const t=COPY[getLang()],p=readProfile();
    text('accountEyebrow',t.accountEyebrow);text('accountTitle',p?t.backTitle:t.createTitle);text('accountIntro',p?t.backIntro:t.createIntro);
    text('accountNameLabel',t.name);text('accountGradeLabel',t.grade);text('accountContinue',t.continue);text('accountNote',t.note);
    const input=$('studentName');if(input)input.placeholder=t.namePh;
    const grade=$('studentGrade');if(grade){const labels=getLang()==='te'?['8వ తరగతి','9వ తరగతి','10వ తరగతి']:['Class 8','Class 9','Class 10'];[...grade.options].forEach((o,i)=>{if(labels[i])o.textContent=labels[i]})}
    if($('accountError'))$('accountError').textContent='';if(input)input.value=p?.name||'';if(grade)grade.value=p?.grade||'8';
  }
  function profileSubmit(){
    const t=COPY[getLang()],name=($('studentName')?.value||'').trim(),grade=$('studentGrade')?.value||'8';
    if(!name){text('accountError',t.enterName);return}
    let p=readProfile();if(!p)p={id:'student_'+Date.now().toString(36),name,grade,createdAt:Date.now()};else{p.name=name;p.grade=grade}
    save(PROFILE_KEY,p);
    let d=readData()||{profile:p,chapter:'Chapter 2 — Linear Equations in One Variable',diagnosis:null,learningPath:null,events:[],skills:{},currentStage:'profile',updatedAt:Date.now()};
    d.profile=p;d.updatedAt=Date.now();save(DATA_KEY,d);record('student_profile_saved',{studentId:p.id});renderDashboard();showScreen('screen-dashboard');
  }
  function persistDiagnosis(){
    const d=readData();if(!d)return;let snap=null;
    try{if(typeof BODHA_DIAGNOSTIC_V068!=='undefined'&&BODHA_DIAGNOSTIC_V068.build){const a=BODHA_DIAGNOSTIC_V068.build();snap={score:a.score,total:a.total,overall:a.overall,targetSkill:a.targetSkill,targetSkillKey:a.targetSkillKey,rows:(a.rows||[]).map(r=>({skill:r.skill,skillKey:r.skillKey,pct:r.pct,statusKey:r.statusKey,confidence:r.confidence||null,gap:r.gap||''}))}}}catch(_){}
    if(!snap&&typeof buildAnalysis==='function'){const a=buildAnalysis();snap={score:a.score,total:a.total,overall:a.overall,targetSkill:a.targetSkill,targetSkillKey:a.targetSkillKey,rows:(a.rows||[]).map(r=>({skill:r.skill,skillKey:r.skillKey,pct:r.pct,statusKey:r.statusKey}))}}
    if(!snap)return;d.diagnosis={...snap,completedAt:Date.now(),answers:(state.answers||[]).map(a=>({...a}))};d.learningPath={targetSkillKey:snap.targetSkillKey,targetSkill:snap.targetSkill,createdAt:Date.now()};d.currentStage='diagnosed';d.skills={};snap.rows.forEach(r=>d.skills[r.skillKey]={...r,lastEvidenceAt:Date.now()});d.updatedAt=Date.now();save(DATA_KEY,d);record('diagnostic_completed',{score:snap.score,total:snap.total,targetSkillKey:snap.targetSkillKey});
  }
  function persistPractice(){
    const d=readData(),p=state?.practice;if(!d||!p||p._dashboardSaved)return;p._dashboardSaved=true;
    const key=p.targetSkillKey,prev=d.skills?.[key]||{},total=p.items?.length||0,pct=total?p.score/total:0;
    d.skills=d.skills||{};d.skills[key]={...prev,skillKey:key,practiceScore:p.score,practiceTotal:total,practicePct:pct,practiceStatus:pct===1?'strong':pct>=.5?'developing':'support',lastPracticeAt:Date.now()};d.currentStage='practicing';d.updatedAt=Date.now();save(DATA_KEY,d);record('practice_completed',{skillKey:key,score:p.score,total});
  }
  function skillName(key,fallback){
    try{const q=(typeof diagnosticQuestions!=='undefined'?diagnosticQuestions:[]).find(x=>x.id===key);if(q?.skill){const v=q.skill[getLang()]||q.skill.en;if(v)return v}}catch(_){}
    return fallback||key||'—';
  }
  function renderDashboard(){
    const d=readData();if(!d||!d.profile)return;const t=COPY[getLang()],p=d.profile,rows=Object.values(d.skills||{}),diagnosed=!!d.diagnosis,practiced=rows.some(r=>r.practiceTotal);
    text('dashEyebrow',t.dashEyebrow);text('dashHome',t.profile);text('dashCurrentLearning',t.current);text('dashSubtitle',t.subtitle);text('dashDiagnosisLabel',t.diagnosis);text('dashDiagnosisNote',t.diagnosisNote);text('dashFocusLabel',t.focus);text('dashFocusNote',t.focusNote);text('dashEventsLabel',t.events);text('dashEventsNote',t.eventsNote);text('dashMapTitle',t.map);text('dashMapBadge',t.evidence);text('dashJourneyTitle',t.journey);text('dashJourneyBadge',t.path);text('dashBoundaryTitle',t.boundary);text('dashBoundaryText',t.boundaryText);text('dashClear',t.reset);
    text('dashGreeting',getLang()==='en'?'Hi, '+p.name+'!':'హాయ్, '+p.name+'!');text('dashChapter',t.chapter);text('dashStage',practiced?t.stagePractice:diagnosed?t.stageReady:t.stageProfile);text('dashNextText',t.nextLabel+': '+(diagnosed?(practiced?t.nextPractice:t.nextLesson):t.nextDiagnosis));text('dashStart',diagnosed?t.continueLearn:t.start);text('dashDiagScore',diagnosed?((d.diagnosis.score??0)+' / '+(d.diagnosis.total??0)):'—');text('dashTarget',d.learningPath?.targetSkillKey?skillName(d.learningPath.targetSkillKey,d.learningPath.targetSkill):'—');text('dashEvents',String(d.events?.length||0));
    const map=$('dashSkillMap');if(map){const display=rows.length?rows:(d.diagnosis?.rows||[]);map.innerHTML=display.length?display.map(r=>{const pct=Math.max(8,Math.round((r.practicePct??r.pct??0)*100)),status=r.practiceStatus||r.statusKey||'developing';return '<div class="dash-skill"><div class="dash-skill-top"><strong>'+skillName(r.skillKey,r.skill)+'</strong><span class="status '+status+'">'+(t.status[status]||t.status.developing)+'</span></div><div class="meter"><span class="'+status+'" style="width:'+pct+'%"></span></div></div>'}).join(''):'<div class="analysis-empty">'+t.empty+'</div>'}
    const steps=t.journeySteps,journey=$('dashJourney');if(journey)journey.innerHTML=steps.map((label,i)=>{const done=i===0||(i===1&&diagnosed)||(i===2&&diagnosed)||(i===3&&practiced),current=!done&&((i===1&&!diagnosed)||(i===2&&diagnosed&&!practiced)||(i===3&&practiced));return '<div class="journey-step '+(done?'done ':'')+(current?'current':'')+'"><span class="journey-dot">'+(done?'✓':i+1)+'</span><span>'+label+'</span></div>'}).join('');
    const note=new Date(d.updatedAt||Date.now()).toLocaleString();text('dashDataNote',getLang()==='en'?'Saved on this device • Last updated '+note+'':'ఈ device లో save అయింది • చివరిసారి '+note+' కి update అయింది');
  }
  function dashboardStart(){const d=readData();if(!d)return;if(!d.diagnosis){showScreen('screen-welcome');return}const key=d.learningPath?.targetSkillKey;if(key&&typeof startLesson==='function'){startLesson(key);return}showScreen('screen-results');if(typeof showResults==='function')showResults()}
  function wire(){
    const start=$('startBtn'),account=$('accountContinue'),dash=$('dashStart'),home=$('dashHome'),clear=$('dashClear');
    if(start)start.onclick=()=>{renderAccount();showScreen('screen-account')};if(account)account.onclick=profileSubmit;if(dash)dash.onclick=dashboardStart;if(home)home.onclick=()=>{renderAccount();showScreen('screen-account')};
    if(clear)clear.onclick=()=>{if(!confirm(getLang()==='en'?'Reset this prototype student data on this device?':'ఈ device లోని prototype student data reset చేయాలా?'))return;localStorage.removeItem(PROFILE_KEY);localStorage.removeItem(DATA_KEY);location.reload()};
    const begin=$('beginDiagnostic');if(begin)begin.addEventListener('click',()=>setTimeout(()=>record('diagnostic_started'),0));
    const next=$('nextQuestion');if(next)next.addEventListener('click',()=>setTimeout(()=>{if(typeof diagnosticQuestions!=='undefined'&&state.currentQ>=diagnosticQuestions.length)persistDiagnosis()},0));
    const finish=$('practiceFinish');if(finish)finish.addEventListener('click',()=>setTimeout(()=>{persistPractice();renderDashboard()},0));
    document.addEventListener('click',e=>{const b=e.target.closest('.lang');if(b)setTimeout(()=>{const id=typeof visibleScreen==='function'?visibleScreen()?.id:null;if(id==='screen-account')renderAccount();if(id==='screen-dashboard')renderDashboard()},0)});
    const p=readProfile();if(p)renderDashboard();
  }
  window.BODHA_DASHBOARD_V077={renderDashboard,renderAccount,persistDiagnosis,persistPractice,loadData:readData};wire();
})();